---
AWSTemplateFormatVersion: 2010-09-09

Description: CI/CD Pipeline

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  ServiceName:
    Description: enter your ServiceName
    Type: String
    Default: "apprunner-test"

  GitRepositoryName:
    Description: enter git repository name
    Type: String
    Default: "apprunner-test"

  BranchName:
    Description: enter git branch name
    Type: String
    Default: "master"

  ECRRepositoryName:
    Description: enter ECR repository name
    Type: String
    Default: apprunner-test

  ArtifactBucketName:
    Description: enter artifact bucket name
    Type: String

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ServiceName}-codebuild
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ServiceName}-CodeBuildRole"
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: "ECR_REPOSITORY_NAME"
            Value: !Ref ECRRepositoryName

  EventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: eb-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource:
                  !Join [
                    "",
                    [
                      "arn:aws:codepipeline:",
                      !Ref "AWS::Region",
                      ":",
                      !Ref "AWS::AccountId",
                      ":",
                      !Ref CodePipeline,
                    ],
                  ]
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - "CodeCommit Repository State Change"
        resources:
          - !Join [
              "",
              [
                "arn:aws:codecommit:",
                !Ref "AWS::Region",
                ":",
                !Ref "AWS::AccountId",
                ":",
                !Ref GitRepositoryName,
              ],
            ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref BranchName
      Targets:
        - Arn:
            !Join [
              "",
              [
                "arn:aws:codepipeline:",
                !Ref "AWS::Region",
                ":",
                !Ref "AWS::AccountId",
                ":",
                !Ref CodePipeline,
              ],
            ]
          RoleArn: !GetAtt EventRole.Arn
          Id: !Sub ${ServiceName}-pipeline

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ServiceName}-codepipeline
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ServiceName}-CodePipelineRole"
      ArtifactStore:
        Location: !Ref ArtifactBucketName
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: source_output
              Configuration:
                RepositoryName: !Ref GitRepositoryName
                BranchName: !Ref BranchName
                PollForSourceChanges: "false"
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: source_output
              Configuration:
                ProjectName: !Ref CodeBuildProject
